In [17]:
import pandas as pd

In [ ]:
orders = pd.read_csv('data/raw/olist_orders_dataset.csv')

Miramos la cantidad de ordenes por mes

In [ ]:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_month'] = orders['order_purchase_timestamp'].dt.to_period('M')
orders_per_month = orders.groupby('order_month').size().reset_index(name='orders_count')

In [5]:
orders_per_month

   order_month order_year  orders_count
0      2016-09       2016             4
1      2016-10       2016           324
2      2016-12       2016             1
3      2017-01       2017           800
4      2017-02       2017          1780
5      2017-03       2017          2682
6      2017-04       2017          2404
7      2017-05       2017          3700
8      2017-06       2017          3245
9      2017-07       2017          4026
10     2017-08       2017          4331
11     2017-09       2017          4285
12     2017-10       2017          4631
13     2017-11       2017          7544
14     2017-12       2017          5673
15     2018-01       2018          7269
16     2018-02       2018          6728
17     2018-03       2018          7211
18     2018-04       2018          6939
19     2018-05       2018          6873
20     2018-06       2018          6167
21     2018-07       2018          6292
22     2018-08       2018          6512
23     2018-09       2018            16
24     2018-10       2018             4

El dataset es inconsistente antes del 2017 y despues de Agosto del 2018.

Filtramos por estas fechas y guardamos en ``data/proc``

In [6]:
orders_filtered = orders[(orders['order_purchase_timestamp'].dt.year >= 2017) & (orders['order_purchase_timestamp'].dt.year <= 2018) & (orders['order_purchase_timestamp'].dt.month <= 8)]
orders_per_month_filtered = orders_filtered.groupby('order_month').size().reset_index(name='orders_count')
orders_per_month_filtered

   order_month order_year  orders_count
0      2017-01       2017           800
1      2017-02       2017          1780
2      2017-03       2017          2682
3      2017-04       2017          2404
4      2017-05       2017          3700
5      2017-06       2017          3245
6      2017-07       2017          4026
7      2017-08       2017          4331
8      2018-01       2018          7269
9      2018-02       2018          6728
10     2018-03       2018          7211
11     2018-04       2018          6939
12     2018-05       2018          6873
13     2018-06       2018          6167
14     2018-07       2018          6292
15     2018-08       2018          6512

In [ ]:
orders_filtered.drop(columns=['order_month'], inplace=True)
orders_filtered.to_csv('data/proc/orders_filtered.csv', index=False)

In [20]:
valid_order_ids = set(orders_filtered['order_id'])
valid_order_ids

{'65959cbdb267c29a5cb0021a367df75c',
 '77d5d33e7905054cee0bdb3dbebe4f1c',
 '6f791d3c2f75ec3ec0e97decd281b0f3',
 '293d3c2a058c0395d19e7d1a4aa87f41',
 '2ef4a11b6e24fdfbb43b92cb5f95edff',
 'adb4641524ad981f9ab1886ee54977c7',
 '327ee18cf93b73d75911ca52f0c73ed4',
 '8accd50880b882387ddd4a36d0b1b7d4',
 'b273023a4d0b9c3457f70b641bd1cf05',
 '76fd5bb49ba9bda8891b61cf1b45f0f2',
 'df65602000ffdf593af0979d8c8a8544',
 '424fede77e7b571eca6ff46a2276f8af',
 '48234093c963b181210813cda29c7e2e',
 '2dd83692621ae4c375eda73168295b17',
 '34280c3bc1c50403f0f1d4b272565256',
 'cf9d814ad8673ebdaec52528c1f7a7ca',
 '22d6af278bac655b75f102132b019564',
 '2b14839ae891517dd0d253279ac79b0e',
 '91eefa3cd52e8361bd4f6106356c6d0c',
 'de1288b53d00f641d4de97992ba09703',
 '0616b1a248556f0f4c5aea97beb0729a',
 'ac1bc75d5621c5b8a9ce8d494de07cdf',
 '43ca8748a71977b9d33696cd909f613f',
 'd1a0874a41563f4f1cb865d11acec8e2',
 'd7a77baab69330a11a384b31591498b3',
 '15d7f7e31e30d22d476a7049de63b2dc',
 'a016702972f9a03256db6aecb30ba538',
 '7970159f69f09e481001d678e5365a1c',
 '26c9c7c372a75607ecbff1e8253f0792',
 '660cb47a0b4b671c86901a47f7dbc91c',
 '971255ac71ca5ab5eccc94b177e081c5',
 '26466061ecf0630db081aea8581b871b',
 '238bcd7a2027e5f32fd185c264d73786',
 '8b5bc96af9b784e1819b28162f0ffffc',
 'fe36a827e3e9e0a6f5e11b0be2055727',
 '5c738a35c11d2bc6e99d39e84dd7102a',
 '11e930fd8da276f30361256c23d58196',
 'dff351d499a7a16d302eb0c77d6fc100',
 'bc7bc14f585b1879f63e89cb0e4cfa17',
 '96cf7ecd8c676d61be261ffdda90b008',
 '9827d07ad9392a9fff10d7b9f6c05f7e',
 '94e43121a0232434f1ee7c1888f2cce5',
 '7d63f6eebe0dba6fbe9a8c9b5d11aa96',
 'f83a57cc6e5cab20740d40eaa72dff00',
 '70b0f3c961935e93c43c76c79bae4596',
 'ae939729c93b0ecd65e284740cb48997',
 '37864e339894159b890ecddc8f7cc55c',
 'fd7f1e5cb7d88c786df9b8026d733572',
 '5a2aaa78e3c69a74dd64b28846deb199',
 'b70b8b3007ddfc929dca4a5c3a183853',
 '70ed892da9da5db41406428e9d9ced49',
 'c056578fe94b80e3f1e732d013df9374',
 '26b5660725133bc74bfe584874b637cc',
 'c76b8b4f31097feb8351e62691177012',
 '498cdac3b77bd13d44a8cfd3e26b768b',
 '8bf8a39f0859c5d00da3d27e8ef39d7f',
 'a9c6c0298a1b91a7e66a387df066e225',
 '6da26425f18bd6e1d4be0e8be50162a3',
 '6c3682387b03809f0cdff2ef08a7cc17',
 '67cfccdc9f8cc58dc90fecf42712731a',
 '30e306d7092ec3bf44efabf012cdd06e',
 '92ea6a0cefc845d92f3b1339e0e0100a',
 '2593934aa67c9cf886bba605ff28c2b8',
 '1eb73d543a6a3318fe766653379d5d4b',
 '46f0668d5961419489c708d57e9e99bb',
 '89ca1c6fae0e21f0395c0e3b1d89914e',
 'd48044395576c3b0d752662aa20cece5',
 'a62edb6b5312cdc742089aa7c336718c',
 'fd6570a375422eb90b25eae62935db7b',
 '708c129b280e719faa3988c41374d4fd',
 'c754e56721e29d971fe4e9a005a3e439',
 'b14127bfb817fb9d5883aacd257bb447',
 '4645204bfe0435a74ce5ada0eb4458ae',
 'b024fdd2d489610af375a0ae22124264',
 '49ac83265a3a9d7d492eb5e1909b485a',
 '82e321af7534ba70a73929d2e4c2cf36',
 '415d3ba51a2cf1ed6c5b722c94f9c4a2',
 '0e52eaa92a794742da29c413a23a7b80',
 'b6b94b1cc59892d36b45ad8df8055206',
 '2320f88fd7982719055be3476e3e8bf3',
 '09bfe605baffbe939fb10d3e8936346e',
 '7900ff338051fc207475b59ae5465060',
 '00a4d94df1c9757661679b2f4bd6d311',
 'ae59ddbdffc31cc10bdb9b2d85d2804f',
 'be6415dd0ae6bbbbd1a4186e22ead10c',
 '5d4b951a36d28b50e981ff69e62e2414',
 '17c059796a89b5b4c53113de933500c1',
 '368be3e65256098afbe3903548d47912',
 '5cc63affb50754b86ebcc046f957c65b',
 '2cd690a78448d2d942353c66dd6f6064',
 'd21bdc8a5aec774d419d8db5455e0ae8',
 '49e209e4415e51644d1f13072b00d8dc',
 'd06353378a1ff1ae9d69e21e97c78906',
 'd1ab8de1e279bd8a55e4135f83d5c599',
 'ab4e9c7509c66adaea2fe37d7e1537c4',
 '0540bf9189ef17aab470c4942f760e78',
 '63906fe0b5159737edaca79de6b80fc1',
 'c0d7ffda628810fb83a35a91d1a21887',
 '1cc0c55f59f96405e1b29fbd9bb91c01',
 '7bbaf5678aa799c667b939cb8a8b0294',
 'd62324319b4efb72f855f123f06cb07f',
 '87ef1d19ade51410879febf6046ea642',
 'b82c29ee4251028bd0891ef9e3fe53b9',
 'e1f37ead3c565a7f54eead433530c790',
 '6b8fb85c27e8d90db257311f74b7c6e7',
 '9c37d7a7de99233fd6490a1c09ba0404',
 '9fa33f47b8defffcb858b25dff6c55e6',
 '36d86e93a8ee82cc4a557ab486743d88',
 '4fea2d9b1556c6f36a21a75b5ba71246',
 'b58c726e8f5ba3196c593b1837d25744',
 'eed169e888ef45d577ec9d8972a597c6',
 '0e66712947a6d0ae935240a304775a17',
 '043c74b543e990bd18b14ef1e4344031',
 'a6145b6681d0b1556afbcf25131f2952',
 '1cde9001045df230785548237295c58b',
 '1248580ae351357ac7a36fc314df5268',
 'f7d5fa83743d8d78c798e7824125ee7f',
 '261e56a43de07e1b1bc9e8615c8e8aa9',
 '49d611a6db43f09965cd45ac828fc656',
 '1c54750859f8472306a0b63d74e782ef',
 'c905910185bc1f8e9c3617ee560770d8',
 'b15acd827ae5109303845f18ff8d4662',
 '7aee2b4a36b8b9f260376a8319900aa7',
 'd5d3b4b504a59a416704978bb72fce3d',
 '7f59962b8f02ca840674b28f1b9cda2b',
 '880e262ca224fc654e306f76653f4d25',
 '62ffb8b5fc46e6cba7ccb763025fd09c',
 '3d9c9af0e623563594ffe17db9a5a486',
 '43d0adacfa785ccb9e7544f2c82c5566',
 'ecc81531d82fb15b1c8fe8bb6ddfb02b',
 '4dddc24327ff6d738f2a72abf2b2bc71',
 '2c5948305d5a014ba38e3bae99c2fa36',
 '6fd9d5b35f04ff5c30e58111b9ecbff4',
 '6a6c30136e870dc8e8338fbb826ee41e',
 'd2dbcdd27c3b2a5db7cdea48cc9d0161',
 '1c38140d4542f0ac92eeafa89c9575c0',
 '9d513821c0477231fc7c1bfd684d13d8',
 '01e4eeac4002b2e57b7ada6bc3a3c38f',
 'cd3f1c4c9d4aaf1ea8940fbb22adced5',
 '902ec12570bd6b13462824125beeda65',
 'abbbf52551bc34cd52a7851c06dfca90',
 '5ee25db3905647605d30aa9aff44782b',
 '896f988855a09982ee61d501ef6543a3',
 '219f831fcedecf53187489f9aad154eb',
 'd341bf71429128ec496e8012f3f8e2a0',
 '3a27e0b9d5d118eeba13571803a2b08e',
 '9a8cd6b0ac8e80fe4e72e9de1aee04cf',
 '531a74ff9a6617b0cae88c4b67646988',
 '987f3d9ad096993454ef3c2c4d9f7a68',
 '6c8409ca697ac1cdf422adf792fbf759',
 '7d1b1cc13d2c22c1cad811b1fafd0537',
 'd9bd19ff1f9e434a5d633944430a97ec',
 '8121a5da48fe0eaf4676e88e9d209cee',
 '85829f8289bff10de3c2cd62170d670f',
 '25de47610b1fe93d066d999828c0fe57',
 '8fbf69d27f719cdac15cafeec686eb37',
 'c67440872252c7c4079023160409025d',
 '26b9d973779b9fe3d4496521aa4d67e9',
 '236c5c6711eb7864803f0f0c739e5c05',
 '271c268d4d21a60bfad6ddb92be3ba3b',
 'c43de9faa95d5014569aa1ec9ac83554',
 'fd58bdbb6cc5d7519e063c3ceb7e951b',
 'fc4e4569c5ee84762423c8111fdea8c7',
 '9f775377f0750b17db861c49f3bcc8d6',
 'ea2a094b786d1184a3b3cf0e5f549d04',
 '8413ac0b09301d03b78adeca5840866f',
 '2e8be4cb1a41afbbe6efc1c84831a55e',
 '1b75e38e0739ccdd08fb7e7cd6fe8342',
 'cf8734286de02dbdf9700cdf2bf07976',
 '6a90c84c2efab9939e578dee122b521c',
 '6844232657c577a7825fa1fdabbb6b5c',
 '061eb3fa9ee22a8dc3c90060e5a637c9',
 '388ef804dd3afbcde7d2ba26480d0bb0',
 '098a17af931400d21917fe24f3346b53',
 '84568d93e897d1d8db26cb9b9d157700',
 '5f766dfc65eff86be5b3015dbce0e2c6',
 'b68657d2b49e65f89329eebfa2742203',
 'f81189aaeb2e561e2e9fe0faec4bbbc3',
 '2adcc6d21c5ae646d76e2a62e1388eb4',
 '1f6a5335ecf1406eea5f2cccc0c5946f',
 '0b61dd71ead1e65e9d50db5b89cb5cc4',
 '80cd775de9b633666bb12df2a3eba10b',
 'ec073f2bd759729986c0da65f688ddc8',
 '69d7a6c47dc11a476f79514694809c60',
 '39957e768826f84b5506dc5b3ca8f655',
 '039749cde6a67a679fa5602f776cefa4',
 'd70442bc5e3cb7438da497cc6a210f80',
 '707e74158c5b971316d037bf93366df5',
 '04f7a2c35c535b543c6042ee73b125f0',
 '5128bbf180434cd939884e273629de98',
 '34bf4feda1e203af64692d97c6950c39',
 'e6fc4ea08434b40ac98a0cb284e5a8eb',
 '46ca3c06a077e293704ad910d2a1b16d',
 '806b3c21802d3221a944281399d2a6a8',
 '533e69dda70ac7671a0bda8bb5fc08db',
 '6d24d19f8842be0e8e1064fb0709528b',
 'ce0102221c8d12a97979c74d09cca282',
 '5943d2b7f07adf0f9bd4dd14b9ecd070',
 '10aa3224bbb698312ca210f229f91b5e',
 '312182e0c020c06cbe244ddb6d4fe780',
 '57e15b65e74748b2b3c1a146dc123d1c',
 '2ec0b57f8588d1cc98ac3aee116d2023',
 '0401f33945d6292657d6a4d951191570',
 '7c33b548f0fee23cb4a8afe1f1333ee8',
 '430d466a33524c9953d7f2e25c6d3f06',
 'e3666b7c6eae23a285267dd0851c5ae1',
 '831e2035989f1b9cb217e1093e2992d3',
 '3e351fbdb9c27ebe3c34cb15c40b7e22',
 '08e4b9181951f803229ff26c157f5045',
 '84fbd5c07d190419428197464cdba60a',
 'd38dcb503cd4ddc6ce7702552918bd8f',
 'bec3652605143e5f7e0265d993793eba',
 '92f4f749aa508d58dee50d9ccdb6c9dd',
 '9aba5a261ecd7b4c4d324ee1ab55cae7',
 '5a50ee4e7bf3b3bf306a1c3f19a1a885',
 '4a14973ad9560660e3962ba5efc1ffaa',
 'f55846241ee01e6a5d8401e58d5b6c77',
 'df6c1db4ad957928715a81ce54563895',
 'ae352cde9779081a0ca9020c7e276325',
 '8e8f8ef29c78c7b9c98cac70dd331ce2',
 '6791e565e137a3933b0f7ba7fba46cf2',
 'ec63c198f700051fb0a74c40a757af0e',
 'afb7c0f7929d4ac3b13a200b2137d90b',
 '82348f1b5f24ac795fa9320e02c49553',
 '33bb79c28616262f5e3fdcf5e678b266',
 'c3d5c6fc77f1986421777d4d61779aca',
 'bd4fdc437a085a99fc75e5346b518aa2',
 '5104ff479c1b5720649c1b85b599d2ef',
 '6e0773d1bf763019a9e1bfc1703f1aa8',
 'ba9db9fb21617fd062fee898664e4996',
 '9eab9b5db2edcd3d67654eea38f74ad9',
 '49af403fd43b8ca8b5f7b74845bf1f66',
 '003edccf16bc5ec447f592913b3df2b4',
 'c77e47704d90425196c86d3e237dd9fa',
 '2ab7caa24a5d02dee343802f4031a20a',
 'd9be5eb6e572c7e2a77db678c9d79aba',
 'bc54eadd50eb0e830200b242f32152bd',
 'abb6950b59e799ed4f6b82c5b2266983',
 '1a7ea14458cd657d2d1355cc8cb2f547',
 'c9ffd64db3f411822cf589bc1a567f0a',
 '02b8fcdd1bd75d7d5861f407dde29768',
 'd2978c1c5c6b9400dfa6a1c08f735314',
 '129832042bc2898155b5ebf3b2058585',
 'ac17fcdce65beed9ddc7473ff8150528',
 '84cf671bc3869df812c782309ef46a8d',
 '00f6ac4816d12f49026b09f2aa77d15f',
 '4cebb64502b3c7295709a972ae314c7c',
 '1f57e9ff5f61f27154f91721393f9615',
 '0345ba423eed2b009e0e407b19c422e4',
 '78fe61feb61fcd8421082ee8888cd93f',
 'a31b5cba0164acdc91b6196825128128',
 '0504c112cd5ef9650a65748c4dc380cb',
 'e327b0b5a08cf398b21ebfd6a36b38c8',
 '8a24246c79463794ce357f7adc2eb5dc',
 '2e3a1177e30ae6d784240896e5441c55',
 'fb7f4f9f554fcd3ae98197ab5e81bb53',
 '1d95cf3b52cc2ad7084239c958274b5c',
 '585350d8134c384f89524f203b747ee0',
 '5b01111319bb33fcc77bb2aef3e938ff',
 '2d1f08f7693e119a191d97d953258189',
 'feef9f21cf88daf192de972212d1c5d5',
 'c915a55221e61e2d798340ec6553d2b0',
 '97e22a7b438827d5a86bc1a9f92d8c83',
 'fd3114978747f92401511144ba65a631',
 '255111c7355b48e49add6f5a16c22483',
 '2446a642fca6873ebfd22332c6657732',
 '3d8f7ae6c3ba35a822e61acf337a4968',
 'a3016f532570aae9cecf667e2a6e06ff',
 '163b53e265c530cded6553a3b5d485cd',
 'c00620529457d989d0a9e9e68062828d',
 'a88edef387e2a7e457695664bf0ddfc0',
 '3cde763f687d3708ba577295e22ca8ad',
 'baf54302abe3b0c2c43c2b55b0212a01',
 '5baeaa8bec54f12f0aa0ee4b4d285cf9',
 'c60c1ff560443153d7f50771e5fe9b92',
 '08030370edeb35f2f91b73f09f76a49b',
 'ffb73c3b138a51d4c3a2b7f60c5f5de7',
 '3514fd00653caace61ea8ad6cd20c017',
 '97d6279a91ffe03ed63041acff508488',
 '5a8a4dc28b16fb90469ad749f9535773',
 '3f14ebe155866508ab24849e541695dc',
 '3129f1c46cd423a817ca16f066a80fb1',
 '3c7ad0e853a5d0f0b08290127e7325a9',
 'e210480a7951a7968ea2a32e38c6dd70',
 '99f1b8c7375ffb25df3f411e1268cd7f',
 'b1060e1be953d38ce9cdf6140c7d27a7',
 'a691df9591603131dd5fa585cd1d9406',
 'c359ea677d56a4dc741b767e413a23f8',
 '44d266dec578366b923e9b3a636c8311',
 'b811c8ca07716586e80c0bc4f2a6e39f',
 '8afe6304c5643864e2b19153a205ae5e',
 '7edf24d26573e36b72c670b3810ab3e0',
 'ce7364e31a5ed0653bfcfc6d7f2b9785',
 '245ddaef16302f47bdda5b7549ea20fe',
 '3b20eefea25e9f7a1f09b7106c26da95',
 '72aae4d8091260674fd5abd94479abc3',
 '12b9b63b911cf0a24b137a184c48e4ee',
 '3bb01fb597afee976918577ed7697c80',
 'cd74cd8f3a1445a29e098dcac4cc8d11',
 '949f11fbfbf9d79c34c7c1f21b3c1c6e',
 'e544389041b93865b618cbe3bd55f445',
 '09a1022dc99a8046b87235a846062035',
 '9263d44e38972f77bc8c17ad8c063fa1',
 '41cb41ef29a6cd8f633cac105998332f',
 'ef3786e4b943b9f011be07df94558161',
 '198d8b83646f4c7c43be3a2e59364f1a',
 '693c6ae1a1ab759aae8dd08ff9eff189',
 '9580960c270d4525b7224af7ef41235a',
 'b2182fb810efdf89531f055b0ffcd885',
 'bfaa65d09b9fd34aa36a23ad90fa7db3',
 '9c37d94303e95d233a4608dabc34f802',
 'c07b8f5324dbc378865ca2d1c9883236',
 '048f4f6b6d2d3bc131665b2440c39f70',
 '412e22f7bfca70106c77569bbe81ed1a',
 'd1b3c3d319347abd31b56c3d894b2b2d',
 'a6885484f375e5b08eef9d9cac53af34',
 'e987b29cdd5c19069d7c65a4eac2a806',
 '370cfb4244f1a15b8d60d32fce42c3fd',
 '0e04c5cca5ec36abd1ab3b2c33fee74d',
 '1c36473b9a0db63449081c0408a96dc8',
 'e44f8bcf1ae28a8f29c2ef7d87466da1',
 '4214cda550ece8ee66441f459dc33a8c',
 'b2f3763408103bc7173bb36ed02dbeea',
 '925610f1667e7ed61145120c16d91b86',
 '5fd8e536596df0210d3e483288529070',
 '4f53691b758958dca780dbbe19dad2ab',
 '297dfeab4cdd5749b9d6485e13e89877',
 '24c88e563ba8b5ed9b8b9ca7b72f3016',
 'c5ddf6be2ae50588b29222f7b1fd84aa',
 '83af889aa8c573153bd3ac6aaf47f1b6',
 'b2b8934746a9afa7b38c8c1f88268ecb',
 '98bc9215b10e8738ca566a0fa7e49b1c',
 '8514ad13664259c7e1bc7cbaa34826f0',
 '736949a08413c4ce4af7e3f75291fb64',
 '70809734fe201ea6db6d4577b84a3022',
 '9f7b07e872a431807e81c38d6328502a',
 'c2fc2e36ac235bd9043a50b1af5466fd',
 'aa6e1f3a2b645a2b22e70084a30d2cd0',
 '2f5b7d28366c2cee7d7d9be0c23136e5',
 'b8739e2347eff7c8473c5b9568fbb221',
 'f8976b3a54975401f39462dde83413a4',
 '7766424657aa0cfbf1703f9550144964',
 'ef97cf414dbb8fe75a919ae7f4a642a9',
 'de623c0b6bb8c160e80eaacc3100433a',
 '5dc59cf95fa0dc97fbe9961d2547b278',
 '7284ecc4524ff324863b12456e842055',
 'b74a912193e9cb61622b15175442807f',
 '26ee148fb7de61a887e22108db88f609',
 'dc6d833bfea9fd5fbb4336fbc918b39b',
 'b5c372b6166768fd040afdb4f18a4b4a',
 'b88097025fac360c0367799f94ab9a66',
 '8df707012e98bba020753efdaca3fef4',
 '7936a41bf78b669273c75ddc50ab7e07',
 'dd5ebf00c3d8b88a41ec9c8450ec59db',
 '5582d9b46edf97ccc2f3b993c39ace3e',
 'ee45911bb0f3165bc61d3cbf92f37506',
 '9d8b5a8e3231c5bed9d2c45e1fbb116d',
 'eb4067cedddfc4c3f7e9616456fc70af',
 '2e24f57cfbde9ac54cad13561f686405',
 '4da691562dbd0818d7655eeb6dc1de84',
 'ba772856bdab971f8c7eae9e03cf8706',
 'd1ee985bf7378b46fd1058b35c8132da',
 '47912b9e87f6d0977dd948e2722435ee',
 'e3b1bcfd93628bc74d612d85e00b3f1e',
 '5485b7aec242643d6d20665586e616e0',
 'd5db5ade6120da8525cd7eac0608d009',
 '9e1b7a7d17aa42da16ee605b5fee2e0a',
 '045abe3dd2d7c962b78a446b053238a6',
 'd5082415db2dc919202b1d0dc63305af',
 'c8fb73e3313c12aa7978cd59adbd0a6a',
 '8394de68d323384a331279fd8a60462e',
 '973bd34d8572bd529ef5b959c1429973',
 'e7c5ccfc34c262f8f9240ade57e01ed7',
 '031e7d4e559a1bf08e71a419aa998d0a',
 '9bdaacec1587fdf0b7c123d64020f552',
 'fbb1a0e5c4ba183f6cac6076920dc097',
 '8a4398f9b38e8023cd570362226cabb9',
 '9c14756d0113f66be55ca07456df3393',
 '0b47f5e9432bd433f8c5cf64e60e6e5f',
 'a8305d2dfd60042d6000b3de3bc533a3',
 '16e4c23dc1892082c649911189c18f27',
 '366fb8cd92296c6541132ab4cbb28bac',
 'd94600e5b855ffe8db3b9bc06e21b1bd',
 '9f495a88e6454713d2963970d7a119ed',
 'd766e3aae9fe7c4abb652d767d0811d6',
 'b1cc2415253bed6a394cec36a9280797',
 '18ed2638b8a18b428d5f0cc575878eb1',
 '51eb2eebd5d76a24625b31c33dd41449',
 'a39f565fb24832fec6f96a476444b02b',
 'e48db3b231e0ad61656e81b4c9311dad',
 'a97107c0b3df262ab4454ad8c3a91d0b',
 '3dd755153da335084e4f2ae10c077b5e',
 'ef6fb04e563be683ade0b04904bf0d39',
 '1d8c9526428c9c7c72e2e5f4b8d43edf',
 'f16e3a8c0140ade96be78de15312125b',
 '6eb56be25b30e83ab182da6a5d616cf8',
 '59d47389a16d7d6ffbd48ec86e4ef776',
 'e84f18bf4ee058607a5dfa5ac98e0317',
 'f148f0d15c9e216159aadb7bffdb0fe7',
 '779c166cb7fc9e9827102ea44e43b6c7',
 'f37d724af2a6e8663e5de52bc2f7acc3',
 '8e572fc4edc8dafc89bb18bf812916e6',
 'd2fdd09f4f50c75c2895a3252f0c7418',
 'c535905a60628bab8a2b2a69375180ed',
 '16155ce5a2e0a989c3a5a173972eae2f',
 'b85614e04ee9ee71f2632faf63ff3ac9',
 'b0a2019225451e417b6cc92baef9fc8c',
 'cdd61af8ec58bfe7f1fe17f86bf64a28',
 '2a08278777d9f1a73321180ce445b630',
 '73cb7b68ebaea36d0678e616423e2618',
 '1409fa8d66178147ed431573330397c0',
 '35b5ebbe9ea1f14657bfdfb4b52d7465',
 '82f02c0da2c53bc9eb14dcfd74038ada',
 'e2f630b53cb2637be372c3810b089868',
 '3745b3f4f984381ce40a6804a2be23ea',
 '397a03ca45a771d2663ae74a6ab74e53',
 '0c92ac263657a43f18927cc6392e3816',
 '7ae3a62a49f6479010163c2153e9bece',
 '8836b763a62342854712072d612d17b9',
 '35b6b0272ca66bd5fef6d110463c40cc',
 'fd425f7c15eb3698f5b96153549b0f04',
 'af392de2586db1645a4044ef1e84c47a',
 'b494f624c631105b24fe497277085909',
 'bec23d0357e57ab1fccb9e62aafc0147',
 'c2c6674097e6b9ea3b322ce6f3e56117',
 'd5242ba9470b26e23e540d936c9c59b0',
 'ef39ac02e696ce34d885bf4479217715',
 '816981834423576036dbac9e4ccf94ad',
 'b9bce1bd4e5e54f9bbfdd26612378e93',
 '7e41af71933a120d6d0fcf9249f19a85',
 'f97c752350c4546ad37ac0e5adf87f93',
 'eaf42d23fedb6d8d7747c8ab44b8784e',
 'b1d045cd447d2961b72e0d67c18f5d94',
 '475681bb16b5cd2f9120136f3ea950e3',
 'b191545cfb775e72c067683831bf4b0f',
 '147858a6d815c446dfb3d11e20019757',
 '83ca3ab77b87118d0a71a84ddfc9e31e',
 '687b6310118e5776dd599634c9dc51fc',
 'f3f436a397e0d4d39a607a4f7866668c',
 'd1c0be9650d4276bd67e6f8cd3af248b',
 '7cdee3742b0259f2780e96bdd9602f0e',
 '106b93e7196f2acfb1f73a326770c843',
 'b6bf0977a04c2f3b84bf63aa0d308b5e',
 'ac8a7a5a2eb68fd70147207a05c5e9d9',
 'a60d97427c94f3cf9e9c338ac3e9aa14',
 'c348c4e34af674e33ac82ad18ce5404c',
 '44e80ef872fd5884851e68555c2ab020',
 '10084ae353466f1c95f62cbacf6168d5',
 'd6af6233aac78108f824d75f4461fa14',
 '115986c6100a117f487af7dd08cbb2ce',
 'f8f45ebeb38088c44d98d201371ea345',
 'cc2a815c27056f7c5770b6a14d422863',
 'f7b794965cc5b6d20c083cc40cf56108',
 'fda1b1848274ffb1bd6f0e53da874592',
 '9ebfcd2bc9b6535e4bd2f4a199ccb665',
 '17b18aa0bfdcebddefdf2d7da5718181',
 'c7b090b5048ef4f18fe02ef328421afd',
 'df830c3266897b412bb8598ecc43c09f',
 '061ba2e2d7544790b6ed6b5b4dd9278c',
 '9c5505df3b3c87d88bef70eaff841ae5',
 '15f18fdc945de59e900faa4d7fab8f15',
 '437ad5a02525073e622a0752d52e8e19',
 'e5141c749e377be251981ba3ff55b1e7',
 '3b4548a30d5cce3104af1dfd6979970d',
 '05bdb94211a1ae1e3734545262f50da3',
 '8851b8f3b3c9736081a17b2f49b4eaec',
 'a3b803010363e5ad20664a8853b1056d',
 'd04690bea446315563a9f2752ff88e9f',
 '055cfc7366f3dfdbca102536d95381bb',
 'f66a94f109a641a3c2a7e7aa4b3269f9',
 '2e90d155b85776a842b3b1c59aa4b340',
 '57d86c396c1d48482e96e9e4a0e14ffb',
 'bc6085fe6b798cce36f61486af007800',
 'e068276f5e75a66212f75b84ebfeaccf',
 'a9016dde97a6a447890dd748aa844b85',
 'a7ddbf4f5ef6befd9d3569b1c34a9605',
 '86290fe54601847212ec62845fb027e5',
 '8321b0cd9de49601b4c81b6ab4c3f15e',
 'fdc16f82eae13ca294b737e810effbfc',
 '1155a271e649284c3e901dbdda76e841',
 '3742355faff03505219c427b01919e0b',
 'a85f6d573e494907ed413a50ba08771b',
 'e275f303e1879be6ec887af2fb5d0e3c',
 '3c116d50bb76160ee1d7a2e8f5791427',
 'fa2327f446a561a540a3fe3069f99046',
 'f73aa9d9da868421ed166e66df561602',
 'bd7ed28cedb8147c71f09e3ab23c369f',
 '725c0e3b1689714b8acfa0b09022e600',
 'ef5c29cd9f6ba37c0363b4d739709b70',
 'a708e05eb2ffa51665826471263f190e',
 '30e608f69bcd3b2758cc9f28c8af087f',
 'bf59b8c2b20f173069f5304326665611',
 '8c1b520fb18c4cd54ac3c058faf000d5',
 'ba77dbce1d3b09b90844c3587248717f',
 '23bab630b11eed4b31aaa2edd31ba773',
 '16b7de5d7e5c3c000744a76ea1861471',
 '4b2dc3d5bb4accd12c73d55b2a10f856',
 '9099e5808d892fd34523293254ddb621',
 '887c6b210d8a2d3a1158dfaaec74e786',
 '947ee6ab639791b5711558a7e55cf98e',
 '7845d9a1a3d511b756a5c2c2352ba770',
 '9cd76a738c425b55aa860a6c5e469857',
 '4c5071751ff07b3f013734d8b4aed882',
 '2f80e75d1ecbb82164966f64abf451fc',
 '6a729d9b8d092428e08072ed4eff6899',
 '92f53cdbef0f16b315c62faa337c4672',
 '728aada863981162c695a2b288d9b410',
 '1109a323a5e20da772a2f7b3cb0f9af7',
 '8604fcfcead42a46d4dddd51bbe86457',
 '5f127aff90e6012e2200e03613eb47cd',
 '79366f58da7efaf2b4717cb46d852fcd',
 '77fb4b8cc3c049b130b87530c7071abd',
 '403990c5fffd698dc79416488b3fb1fa',
 'f3f00047607e23b2b33f81618622a7a4',
 '172d924daf19043deff749396e9eebf3',
 'cf6af03cfe2aa7ce2b23c2b77c1ff722',
 '7ce709f07a1593a395e419ec63e8a766',
 'c7dd323224f4c34e9014d0a89e987b47',
 '5b5270acff888d4eaf14966f98eabd54',
 'c63d42eaa9f87b513dcf03cce7097bea',
 '67660568d9fc745c94e03b88efcf3571',
 'fdef371165dea256526258defc0b326d',
 '2475c5c954f98701b93b7ceb0f5bb669',
 '8b4a1a6f0e8e8695feba49f260195ee8',
 'be8f81fbf4bdf643e1f5548aa269bbef',
 '503e8daafed23dbae78ff210f2d41f0f',
 'ca929fa6d3db41b0d698c716875ccd26',
 'e7d112a19f81eb693360bd433f03625f',
 'aebdb2fcb57815c39468a17e0baacbef',
 '6635b3b5c0e7f509b5b523f0527b81f5',
 '821e2d51e9088af9975ede10f80a04a3',
 '04a0e5cbdfc606ebca72c5b78caf81fe',
 '91c3ea3f720dd9cc12b762347379b0eb',
 'cca0fdbe32d86d386a95c02433412640',
 '6f1651e4c1a0b1e952c2510138563e47',
 'c61f24b4d04a247a7b8f182d3bdb7e18',
 '68b3cbc68e4cd1fe19bec35f1d3bb7ee',
 'cd765bd17903ea30da9a83f9c0532d16',
 '1c80798b60e75536e4c008facd7e9263',
 'b82f05ed1c1a8045489ff9ee86415c9c',

In [21]:
order_payments = pd.read_csv('data/raw/olist_order_payments_dataset.csv')
order_items = pd.read_csv('data/raw/olist_order_items_dataset.csv')
order_reviews = pd.read_csv('data/raw/olist_order_reviews_dataset.csv')

In [22]:
order_payments_df = order_payments[order_payments['order_id'].isin(valid_order_ids)]
order_items_df   = order_items[order_items['order_id'].isin(valid_order_ids)]
order_reviews_df = order_reviews[order_reviews['order_id'].isin(valid_order_ids)]

In [23]:
order_payments_df.to_csv('data/proc/olist_order_payments_dataset.csv', index=False)
order_items_df.to_csv('data/proc/olist_order_items_dataset.csv', index=False)
order_reviews_df.to_csv('data/proc/olist_order_reviews_dataset.csv', index=False)